version: '3.9'

services:

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dummypassword
      POSTGRES_USER: shadowapi
      POSTGRES_DB: shadowapi

  main-server:
    build:
      dockerfile: ./main.Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - 4001:4001

  shadow-server:
    build:
      dockerfile: ./shadow.Dockerfile
    shm_size: 128mb
    restart: always
    ports:
      - 4002:4002
